"""User-facing rules for rules_bun.

Two pieces:

  * `bun_test` — runs `bun test` as a hermetic Bazel test action with
    explicit srcs + deps. Returns a `BunTestInfo` provider wrapping
    the test result file (for downstream consumers; the main consumer
    is the test framework, which only cares about exit codes).

  * `bun_run` — sh_binary macro: `bazel run //path:NAME` invokes
    `bun run <script>` against the live workspace source. Intentionally
    non-hermetic (escapes the runfiles sandbox) for the dev loop.
    Counterpart to `bun_test`'s hermetic execution.

Both resolve the Bun binary via `@rules_bun//bun:toolchain_type` (set
up by `register_toolchains("@bun//:bun_toolchain_def")` in your
MODULE.bazel).
"""

load("@rules_shell//shell:sh_binary.bzl", _sh_binary = "sh_binary")

BunTestInfo = provider(
    doc = "Result metadata for a `bun test` run.",
    fields = {
        "result": "File: the captured test output (stdout + stderr concatenated).",
    },
)

# -----------------------------------------------------------------------------
# bun_test — hermetic `bun test` as a Bazel test.
# -----------------------------------------------------------------------------

def _bun_test_impl(ctx):
    bun = ctx.toolchains["@rules_bun//bun:toolchain_type"].buninfo.bun

    # Bun's test runner accepts a list of files / glob patterns. We
    # pass all `srcs` explicitly so Bazel sees the exact inputs.
    test_args = []
    for src in ctx.files.srcs:
        test_args.append(src.short_path)

    # Build the runner script. Bun reads `bunfig.toml` from the cwd if
    # present; we put it in the sandbox alongside the test files so
    # consumers' bunfig is honored.
    runner = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(
        output = runner,
        is_executable = True,
        content = """\
#!/usr/bin/env bash
# Generated by bun_test.
set -euo pipefail

RUNFILES_DIR="${{RUNFILES_DIR:-$0.runfiles}}"
BUN_BIN="${{RUNFILES_DIR}}/{bun_short}"
if [[ ! -x "$BUN_BIN" ]]; then
  # Fallback for workspaces with non-default repo names.
  BUN_BIN="$(find "$RUNFILES_DIR" -name bun -type f -perm -u+x | head -1)"
fi

# Determinism + telemetry pins.
export NO_COLOR=1
export DO_NOT_TRACK=1
export BUN_INSTALL_NO_TRACK=1

exec "$BUN_BIN" test {test_args}
""".format(
            bun_short = bun.short_path,
            test_args = " ".join(['"$0.runfiles/_main/' + a + '"' for a in test_args]),
        ),
    )

    runfiles = ctx.runfiles(files = [bun] + ctx.files.srcs + ctx.files.data)
    return [
        DefaultInfo(executable = runner, runfiles = runfiles),
    ]

bun_test = rule(
    implementation = _bun_test_impl,
    test = True,
    attrs = {
        "srcs": attr.label_list(
            allow_files = True,
            mandatory = True,
            doc = "Test files (typically `*.test.ts`, `*.test.js`). Each is " +
                  "passed to `bun test` explicitly so Bazel tracks them as " +
                  "inputs.",
        ),
        "data": attr.label_list(
            allow_files = True,
            doc = "Additional runtime inputs (fixtures, bunfig.toml, etc.).",
        ),
    },
    toolchains = ["@rules_bun//bun:toolchain_type"],
    doc = "Run `bun test` over the listed source files as a Bazel test target.",
)

# -----------------------------------------------------------------------------
# bun_run — sh_binary wrapper around `bun run <script>`.
# -----------------------------------------------------------------------------

def bun_run(name, script, args = None, **kwargs):
    """Invoke `bun run <script>` against the live workspace source.

    Escapes the runfiles sandbox via BUILD_WORKSPACE_DIRECTORY so Bun
    resolves modules + reads files from the user's actual source tree.
    Intentionally NOT hermetic — that's `bun_test`'s job.

    Args:
      name: target name.
      script: package-relative path to the Bun script entry point.
      args: extra args passed to `bun run` after the script name.
      **kwargs: forwarded to the underlying `sh_binary`.
    """
    extra = " ".join(args) if args else ""
    _sh_binary(
        name = name,
        srcs = ["@rules_bun//bun/private:bun_run.sh"],
        data = ["@bun//:bun"],
        env = {
            "BUN_RUN_SCRIPT": script,
            "BUN_RUN_EXTRA_ARGS": extra,
        },
        **kwargs
    )
