"""User-facing rules for rules_bun.

Four pieces:

  * `bun_test` — runs `bun test` as a hermetic Bazel test action with
    explicit srcs + deps. Returns a `BunTestInfo` provider wrapping
    the test result file (for downstream consumers; the main consumer
    is the test framework, which only cares about exit codes).

  * `bun_run` — sh_binary macro: `bazel run //path:NAME` invokes
    `bun run <script>` against the live workspace source. Intentionally
    non-hermetic (escapes the runfiles sandbox) for the dev loop.
    Counterpart to `bun_test`'s hermetic execution.

  * `bun_bundle` — bundle a JS/TS entry point into one self-contained
    file with `bun build`. Returns `BunBundleInfo`.

  * `bun_compile` — compile a JS/TS entry point into a standalone native
    executable with `bun build --compile` (Bun runtime + bundled JS).
    Returns `BunBinaryInfo` and is `bazel run`-nable.

All resolve the Bun binary via `@rules_bun//bun:toolchain_type` (set
up by `register_toolchains("@bun//:bun_toolchain_def")` in your
MODULE.bazel). `bun_bundle` / `bun_compile` additionally take a `driver`
js_binary whose entry point is `@rules_bun//bun:bun-build-driver` and
whose `data` stages the build entry plus its full linked node_modules
closure — aspect_rules_js materializes that closure into the action's
runfiles so Bun resolves the import graph natively (no `bun install`).
"""

load("@rules_shell//shell:sh_binary.bzl", _sh_binary = "sh_binary")

BunTestInfo = provider(
    doc = "Result metadata for a `bun test` run.",
    fields = {
        "result": "File: the captured test output (stdout + stderr concatenated).",
    },
)

# -----------------------------------------------------------------------------
# bun_test — hermetic `bun test` as a Bazel test.
# -----------------------------------------------------------------------------

def _bun_test_impl(ctx):
    bun = ctx.toolchains["@rules_bun//bun:toolchain_type"].buninfo.bun

    # Bun's test runner accepts a list of files / glob patterns. We
    # pass all `srcs` explicitly so Bazel sees the exact inputs.
    test_args = []
    for src in ctx.files.srcs:
        test_args.append(src.short_path)

    # Build the runner script. Bun reads `bunfig.toml` from the cwd if
    # present; we put it in the sandbox alongside the test files so
    # consumers' bunfig is honored.
    runner = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(
        output = runner,
        is_executable = True,
        content = """\
#!/usr/bin/env bash
# Generated by bun_test.
set -euo pipefail

RUNFILES_DIR="${{RUNFILES_DIR:-$0.runfiles}}"
# Under bzlmod the toolchain Bun is an external repo file, so its
# short_path is `../rules_bun++bun+bun/bun`. Runfiles are rooted at the
# main repo (`_main/`), so prefix with `_main/` — the embedded `../`
# then resolves back out to the sibling external repo dir. (Without the
# `_main/` prefix the `../` escapes the runfiles tree entirely.)
BUN_BIN="${{RUNFILES_DIR}}/_main/{bun_short}"
if [[ ! -x "$BUN_BIN" ]]; then
  # Fallback for workspaces with non-default repo names. `-L` follows
  # the runfiles symlink to the real (executable) Bun binary.
  BUN_BIN="$(find -L "$RUNFILES_DIR" -name bun -type f -perm -u+x | head -1)"
fi

# Determinism + telemetry pins.
export NO_COLOR=1
export DO_NOT_TRACK=1
export BUN_INSTALL_NO_TRACK=1

exec "$BUN_BIN" test {test_args}
""".format(
            bun_short = bun.short_path,
            test_args = " ".join(['"${RUNFILES_DIR}/_main/' + a + '"' for a in test_args]),
        ),
    )

    runfiles = ctx.runfiles(files = [bun] + ctx.files.srcs + ctx.files.data)
    return [
        DefaultInfo(executable = runner, runfiles = runfiles),
    ]

bun_test = rule(
    implementation = _bun_test_impl,
    test = True,
    attrs = {
        "srcs": attr.label_list(
            allow_files = True,
            mandatory = True,
            doc = "Test files (typically `*.test.ts`, `*.test.js`). Each is " +
                  "passed to `bun test` explicitly so Bazel tracks them as " +
                  "inputs.",
        ),
        "data": attr.label_list(
            allow_files = True,
            doc = "Additional runtime inputs (fixtures, bunfig.toml, etc.).",
        ),
    },
    toolchains = ["@rules_bun//bun:toolchain_type"],
    doc = "Run `bun test` over the listed source files as a Bazel test target.",
)

# -----------------------------------------------------------------------------
# bun_run — sh_binary wrapper around `bun run <script>`.
# -----------------------------------------------------------------------------

def bun_run(name, script, args = None, **kwargs):
    """Invoke `bun run <script>` against the live workspace source.

    Escapes the runfiles sandbox via BUILD_WORKSPACE_DIRECTORY so Bun
    resolves modules + reads files from the user's actual source tree.
    Intentionally NOT hermetic — that's `bun_test`'s job.

    Args:
      name: target name.
      script: package-relative path to the Bun script entry point.
      args: extra args passed to `bun run` after the script name.
      **kwargs: forwarded to the underlying `sh_binary`.
    """
    extra = " ".join(args) if args else ""
    _sh_binary(
        name = name,
        srcs = ["@rules_bun//bun/private:bun_run.sh"],
        data = ["@bun//:bun"],
        env = {
            "BUN_RUN_SCRIPT": script,
            "BUN_RUN_EXTRA_ARGS": extra,
        },
        **kwargs
    )

# -----------------------------------------------------------------------------
# bun_bundle / bun_compile — `bun build` driven via a js_binary driver.
# -----------------------------------------------------------------------------

BunBundleInfo = provider(
    doc = "A single-file bundle produced by `bun build`.",
    fields = {
        "bundle": "File: the bundled output.",
        "format": "string: the Bun output format (esm/cjs/iife).",
    },
)

BunBinaryInfo = provider(
    doc = "A standalone native executable produced by `bun build --compile`.",
    fields = {
        "binary": "File: the standalone executable.",
        "target": "string: the Bun compile target triple (empty = host).",
    },
)

def _driver_args(ctx, out, compile):
    """Build the shared `bun-build-driver` arg list for an action.

    The driver (a js_binary) does NOT chdir into the `_main` runfiles root, so
    `--bun` and `--out` are passed execroot-relative; the driver re-anchors them
    on `$JS_BINARY__EXECROOT` (absolute) so they survive its own chdir into the
    workspace runfiles root. `--entry` stays relative to that runfiles root.
    """
    args = ctx.actions.args()
    bun = ctx.toolchains["@rules_bun//bun:toolchain_type"].buninfo.bun
    args.add("--bun", bun.path)
    args.add("--entry", ctx.attr.entry)
    args.add("--out", out.path)
    args.add("--format", ctx.attr.format if hasattr(ctx.attr, "format") else "esm")
    args.add("--target", ctx.attr.target)
    for ext in ctx.attr.external:
        args.add("--external", ext)
    if compile:
        args.add("--compile")
    return args, bun

def _bun_bundle_impl(ctx):
    out = ctx.outputs.out
    args, bun = _driver_args(ctx, out, compile = False)

    ctx.actions.run(
        outputs = [out],
        inputs = [bun],
        executable = ctx.executable.driver,
        arguments = [args],
        # aspect_rules_js's js_binary launcher reads BAZEL_BINDIR at startup.
        # "." keeps it at the `_main` runfiles root, where the linked
        # node_modules + the bundle entry are staged.
        env = {"BAZEL_BINDIR": "."},
        mnemonic = "BunBundle",
        progress_message = "Bundling %s with Bun" % ctx.label,
    )

    return [
        DefaultInfo(files = depset([out])),
        BunBundleInfo(bundle = out, format = ctx.attr.format),
    ]

bun_bundle = rule(
    implementation = _bun_bundle_impl,
    attrs = {
        "driver": attr.label(
            executable = True,
            cfg = "target",
            mandatory = True,
            doc = "A `js_binary` whose entry point is " +
                  "`@rules_bun//bun:bun-build-driver` and whose `data` stages " +
                  "the bundle entry + its full linked node_modules closure. " +
                  "Run as the action executable so its runfiles materialize.",
        ),
        "entry": attr.string(
            mandatory = True,
            doc = "Path of the entry point relative to the driver's `_main` " +
                  "runfiles root (e.g. `packages/aion-cli/index.js`).",
        ),
        "out": attr.output(
            mandatory = True,
            doc = "The single bundled output file (conventionally `*.mjs`).",
        ),
        "format": attr.string(
            default = "esm",
            values = ["esm", "cjs", "iife"],
            doc = "Bun `--format`. Defaults to `esm` so `import.meta` in deps " +
                  "stays valid under Node.",
        ),
        "target": attr.string(
            default = "node",
            values = ["node", "browser", "bun"],
            doc = "Bun `--target`: the intended execution environment for the " +
                  "bundle. Defaults to `node`.",
        ),
        "external": attr.string_list(
            default = [],
            doc = "Module names to exclude from the bundle (passed as " +
                  "`--external <name>`, repeatable). Use for native addons and " +
                  "runtime `require`s that must stay external, e.g. " +
                  "`pg-native`, `@aws-sdk/*`, `encoding`, `source-map-support`.",
        ),
    },
    toolchains = ["@rules_bun//bun:toolchain_type"],
    doc = "Bundle a JS/TS entry into one file via the hermetic Bun toolchain.",
)

def _bun_compile_impl(ctx):
    out = ctx.outputs.out
    args, bun = _driver_args(ctx, out, compile = True)

    ctx.actions.run(
        outputs = [out],
        inputs = [bun],
        executable = ctx.executable.driver,
        arguments = [args],
        env = {"BAZEL_BINDIR": "."},
        mnemonic = "BunCompile",
        progress_message = "Compiling %s with Bun" % ctx.label,
    )

    return [
        # The output is itself the runnable executable, so `bazel run` works.
        DefaultInfo(files = depset([out]), executable = out),
        BunBinaryInfo(binary = out, target = ctx.attr.target),
    ]

bun_compile = rule(
    implementation = _bun_compile_impl,
    executable = True,
    attrs = {
        "driver": attr.label(
            executable = True,
            cfg = "target",
            mandatory = True,
            doc = "A `js_binary` whose entry point is " +
                  "`@rules_bun//bun:bun-build-driver` and whose `data` stages " +
                  "the build entry + its full linked node_modules closure. " +
                  "Run as the action executable so its runfiles materialize.",
        ),
        "entry": attr.string(
            mandatory = True,
            doc = "Path of the entry point relative to the driver's `_main` " +
                  "runfiles root (e.g. `apps/studio-cli/index.js`).",
        ),
        "out": attr.output(
            mandatory = True,
            doc = "The standalone executable output. On `--target " +
                  "bun-windows-*` give it a `.exe` suffix.",
        ),
        "target": attr.string(
            default = "",
            doc = "Bun compile target triple. Empty (the default) compiles " +
                  "for the host platform. Cross-compile values: " +
                  "`bun-linux-x64`, `bun-linux-x64-modern`, " +
                  "`bun-linux-x64-baseline`, `bun-linux-arm64`, " +
                  "`bun-darwin-x64`, `bun-darwin-arm64`, `bun-windows-x64`, " +
                  "and the `*-musl` libc variants (e.g. `bun-linux-x64-musl`). " +
                  "A future enhancement could derive this from the Bazel " +
                  "`--platforms` via a transition; for v1 pass the string.",
        ),
        "external": attr.string_list(
            default = [],
            doc = "Module names to keep external (`--external <name>`, " +
                  "repeatable). NOTE: native `.node` addons are NOT embedded " +
                  "by `--compile` — list them here and provide the `.node` " +
                  "files at runtime alongside the produced binary.",
        ),
    },
    toolchains = ["@rules_bun//bun:toolchain_type"],
    doc = "Compile a JS/TS entry into a standalone native executable " +
          "(Bun runtime + bundled JS) via `bun build --compile`.",
)
